### ISSUE TITLE
Поле "Возраст ребенка"

### ISSUE THREAD

**Issue by sedan** [AlexanderBogdan/symfocommerce#2]
Добавить в товар "Ограничение по возрасту".

Два поля:
От: ...
До: ...

Значения:
- 3 месяца
- 6 месяцев
- 9 месяцев
- 12 месяцев (1 год)
- 18 месяцев (1.5 года)
- 2 года
- 3 года
- ...
- 16 лет

**Comment by DarthTonn** [comment]
@sedan нужно прописывать проверку на то, чтоб "от" было меньше "до" ?

**Comment by sedan** [comment]
@DarthTonn да, должно быть "больше или равно" (если оба значения указаны)

**Comment by DarthTonn** [comment]
1h
