### ISSUE TITLE
Интеграция CKEditor

### ISSUE THREAD

**Issue by sedan** [AlexanderBogdan/symfocommerce#5]
https://github.com/egeloen/IvoryCKEditorBundle

Обеспечить поддержку CKEditor для его дальнейшего использования в полях типа textarea

**Comment by DarthTonn** [comment]
5m

**Comment by sedan** [comment]
@DarthTonn а где коммит?

**Comment by DarthTonn** [comment]
@sedan не залил с рабочего, сори
