### ISSUE TITLE
Поле "Старая цена"

### ISSUE THREAD

**Issue by sedan** [AlexanderBogdan/symfocommerce#7]
Добавить необязательное поле "Старая цена" (которое будет выводиться как зачеркнутое)

Правило валидации - не может быть меньше чем текущая цена

**Comment by DarthTonn** [comment]
1h

**Comment by sedan** [comment]
https://github.com/AlexanderBogdan/symfocommerce/commit/f61c6354b8d6b7b3424c76868d85c510ba5dfbd0#commitcomment-20684211
